package com.company.Enums;

public enum ID {
    Buff,
    Curse,
    Monster,
    Player1,
    Player2,
    Player1_Slot1,
    Player1_Slot2,
    Player1_Slot3,
    Player1_Slot4,
    Player1_Slot5,
    Player2_Slot1,
    Player2_Slot2,
    Player2_Slot3,
    Player2_Slot4,
    Player2_Slot5,
    Player1_HandSlot1,
    Player1_HandSlot2,
    Player1_HandSlot3,
    Player1_HandSlot4,
    Player1_HandSlot5,
    Player1_HandSlot6,
    Player1_HandSlot7,
    Player1_HandSlot8,
    Player2_HandSlot1,
    Player2_HandSlot2,
    Player2_HandSlot3,
    Player2_HandSlot4,
    Player2_HandSlot5,
    Player2_HandSlot6,
    Player2_HandSlot7,
    Player2_HandSlot8,
    Player1_Deck,
    Player2_Deck,
    Dragging_Slot;
}
