package com.company.Classes;

public enum ID {
    Buff,
    Curse,
    Monster,
    Player1,
    Player2,
    Player1_Slot1,
    Player1_Slot2,
    Player1_Slot3,
    Player1_Slot4,
    Player1_Slot5,
    Player2_Slot1,
    Player2_Slot2,
    Player2_Slot3,
    Player2_Slot4,
    Player2_Slot5,
    Player1_HandSlot1,
    Player1_HandSlot2,
    Player1_HandSlot3,
    Player1_HandSlot4,
    Player1_HandSlot5,
    Player1_HandSlot6,
    Player1_HandSlot7,
    Player1_HandSlot8,
    Monster_1,
    Monster_2,
    Monster_3,
    Monster_4,
    Monster_5,
    Monster_6,
    Monster_7,
}
